python -c "import tensorflow;print(tensorflow.__version__)"
python -c "import torch;print(torch.__version__)"
python -c "import transformers;print(transformers.__version__)"
#python -c "import flair;print(flair.__version__)"
python -c "import spacy;print(spacy.__version__);ner_model = spacy.load('en_core_web_sm')"
python -c "import gensim;print(gensim.__version__)"
python -c "import sklearn;print(sklearn.__version__)"
python -c "import nltk;from nltk.corpus import wordnet"

#python -c "import chainer;print(chainer.__version__)"